version: "3"

services:
  db:
    container_name: "postgres-react"
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cedup
      - POSTGRES_PASSWORD=cedup
      - POSTGRES_DB=cedup
    volumes:
      - ./data:/data/postgres
    networks:
      - test-network

  app1:
    container_name: "projeto-react"
    build: .
    command: npm start
    networks:
      - test-network
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    restart: always


  pgadm:
    image: dpage/pgadmin4
    container_name: "postgres-pgadm"
    ports:
      - "82:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=alaniunkes123@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=cedup
    networks:
      - test-network
    depends_on:
      - db

  frontend:
    image: dpage/frontend
    container_name: "frontend-project"
    build: C:\Users\Alan\cedup\frontend
    depends_on: 
    - app1
    ports:
      - "3004:3001"
    volumes:
      - .:/usr/app
    restart: always
    networks:
      - test-network

networks:
  test-network:
    driver:
      bridge